const CUSTOM_ANIMES = [
  {
    "id": "custom_188",
    "tmdb_id": null,
    "name": "განდევნილი რეინკარნირებული მძიმე რაინდი თამაშის ცოდნით უძლეველი ხდება (the banished reincarnated heavy knight is unrivaled with game knowledge)",
    "original_name": "the banished reincarnated heavy knight is unrivaled with game knowledge",
    "poster_path": "https://animetv.ge/uploads/posts/2026-07/12312321.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/188-the-banished-reincarnated-heavy-knight-is-unrivaled-with-game-knowledge-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_181",
    "tmdb_id": 285993,
    "name": "შავი ჩირაღდანი (black torch)",
    "original_name": "black torch",
    "poster_path": "https://image.tmdb.org/t/p/w342/iWTBUy7tyJVnzSLFuV6os5G0J04.jpg",
    "media_type": "tv",
    "year": "2026",
    "animetv_url": "https://animetv.ge/181-black-torch-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_190",
    "tmdb_id": 296437,
    "name": "საზღვრისპირა ლორდი, რომელიც ნულოვანი მოსახლეობით იწყებს (ryōmin 0 nin start no henkyō ryōshu sama)",
    "original_name": "ryōmin 0 nin start no henkyō ryōshu sama",
    "poster_path": "https://image.tmdb.org/t/p/w342/vHTHQZy3JhgoVMkbXlOot5gOUzZ.jpg",
    "media_type": "tv",
    "year": "2026",
    "animetv_url": "https://animetv.ge/190-ryōmin-0-nin-start-no-henkyō-ryōshu-sama-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_189",
    "tmdb_id": 284581,
    "name": "უძლიერესი უსარგებლო პრინცის ფარული ბრძოლა ტახტისთვის (saikyou degarashi ouji no anyaku teii arasoi)",
    "original_name": "saikyou degarashi ouji no anyaku teii arasoi",
    "poster_path": "https://image.tmdb.org/t/p/w342/1h0g4w6Vh0RenRga2bmtNXT08R0.jpg",
    "media_type": "tv",
    "year": "2026",
    "animetv_url": "https://animetv.ge/189-saikyou-degarashi-ouji-no-anyaku-teii-arasoi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_185",
    "tmdb_id": 235930,
    "name": "Devil May Cry: სეზონი 2 (devil may cry)",
    "original_name": "devil may cry",
    "poster_path": "https://image.tmdb.org/t/p/w342/mX9tqfpjqwreONJHhap7SnSSowe.jpg",
    "media_type": "tv",
    "year": "2025",
    "animetv_url": "https://animetv.ge/185-devil-may-cry-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_173",
    "tmdb_id": 31724,
    "name": "კოდი გეასი: ამბოხებული ლულუში სეზონი 1 (code geass)",
    "original_name": "code geass",
    "poster_path": "https://image.tmdb.org/t/p/w342/x316WCogkeIwNY4JR8zTCHbI2nQ.jpg",
    "media_type": "tv",
    "year": "2006",
    "animetv_url": "https://animetv.ge/173-code-geass-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_150",
    "tmdb_id": null,
    "name": "ღამის გამოძახილი სეზონი 2 (ღამის გამოძახილი სეზონი 2)",
    "original_name": "ღამის გამოძახილი სეზონი 2",
    "poster_path": "https://animetv.ge/uploads/posts/2026-06/gamis-gamozakhili.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/150-ღამის-გამოძახილი-სეზონი-2.html",
    "is_custom": true
  },
  {
    "id": "custom_182",
    "tmdb_id": 297826,
    "name": "ტომბ რაიდერი მეფე: სეზონი 1 (tomb raider king)",
    "original_name": "tomb raider king",
    "poster_path": "https://image.tmdb.org/t/p/w342/xDW6cor12UD0b2IqboQWnrIn0UO.jpg",
    "media_type": "tv",
    "year": "2026",
    "animetv_url": "https://animetv.ge/182-tomb-raider-king-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_157",
    "tmdb_id": null,
    "name": "უძლეველი ჰელსინგი (უძლეველი ���ელსინგი)",
    "original_name": "უძლეველი ���ელსინგი",
    "poster_path": "https://animetv.ge/uploads/posts/2026-03/hellsing_ultimate_new0.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/157-უძლეველი-���ელსინგი.html",
    "is_custom": true
  },
  {
    "id": "custom_127",
    "tmdb_id": 315288,
    "name": "მებრძოლი სული: სეზონი 3 (hajime no ippo rising)",
    "original_name": "hajime no ippo rising",
    "poster_path": "https://image.tmdb.org/t/p/w342/4aUO7AgGqh2KZcNBljr2cE0EVuC.jpg",
    "media_type": "tv",
    "year": "2013",
    "animetv_url": "https://animetv.ge/127-hajime-no-ippo-rising-season-3-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_176",
    "tmdb_id": 235930,
    "name": "Devil May Cry: სეზონი 1 (devil may cry)",
    "original_name": "devil may cry",
    "poster_path": "https://image.tmdb.org/t/p/w342/mX9tqfpjqwreONJHhap7SnSSowe.jpg",
    "media_type": "tv",
    "year": "2025",
    "animetv_url": "https://animetv.ge/176-devil-may-cry-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_184",
    "tmdb_id": null,
    "name": "ახალგაზრდობის გზა (ao haru ride akhalgazrdobis gza blue spring ride)",
    "original_name": "ao haru ride akhalgazrdobis gza blue spring ride",
    "poster_path": "https://animetv.ge/uploads/posts/2026-06/1781180687.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/184-ao-haru-ride-akhalgazrdobis-gza-blue-spring-ride-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_183",
    "tmdb_id": null,
    "name": "მითხარი რომ გიყვარვარ (sukitte ii na yo mitkhari rom giyvarvar say i love you)",
    "original_name": "sukitte ii na yo mitkhari rom giyvarvar say i love you",
    "poster_path": "https://animetv.ge/uploads/posts/2026-06/1781178438.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/183-sukitte-ii-na-yo-mitkhari-rom-giyvarvar-say-i-love-you-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_10",
    "tmdb_id": 46260,
    "name": "ნარუტო (naruto)",
    "original_name": "naruto",
    "poster_path": "https://image.tmdb.org/t/p/w342/1GVfX7kqIbQBp38Riiy1QLQkhJQ.jpg",
    "media_type": "tv",
    "year": "2002",
    "animetv_url": "https://animetv.ge/10-naruto-qartulad-narutos-bavshvoba.html",
    "is_custom": true
  },
  {
    "id": "custom_174",
    "tmdb_id": 30981,
    "name": "მონსტრი (monster)",
    "original_name": "monster",
    "poster_path": "https://image.tmdb.org/t/p/w342/n5XNKXnoXpoXyfiCtXHOf8q8PFM.jpg",
    "media_type": "tv",
    "year": "2004",
    "animetv_url": "https://animetv.ge/174-monster-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_153",
    "tmdb_id": 40424,
    "name": "ინიციალი დი: მეხუთე საფეხური (initial d fifth stage)",
    "original_name": "initial d fifth stage",
    "poster_path": "https://image.tmdb.org/t/p/w342/2TRN7AXN4rRJNIf1TLgIGRVlQZB.jpg",
    "media_type": "tv",
    "year": "1998",
    "animetv_url": "https://animetv.ge/153-initial-d-fifth-stage-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_175",
    "tmdb_id": 63145,
    "name": "შარლოტა (charlotte)",
    "original_name": "charlotte",
    "poster_path": "https://image.tmdb.org/t/p/w342/udiCs1RBGfda1z52cBxu8j9JNmP.jpg",
    "media_type": "tv",
    "year": "2015",
    "animetv_url": "https://animetv.ge/175-charlotte-qartulad-sharlota-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_171",
    "tmdb_id": null,
    "name": "91 დღე (91 dge)",
    "original_name": "91 dge",
    "poster_path": "https://animetv.ge/uploads/posts/2026-06/91-days.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/171-91-dge-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_170",
    "tmdb_id": null,
    "name": "ფერადი დღეები (feradi dgeebi)",
    "original_name": "feradi dgeebi",
    "poster_path": "https://animetv.ge/uploads/posts/2026-05/1625676163_poster.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/170-feradi-dgeebi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_169",
    "tmdb_id": 1167912,
    "name": "ტალღა (talga)",
    "original_name": "talga",
    "poster_path": "https://image.tmdb.org/t/p/w342/mv86H2NkgHzggcjgAVNRH1JU4Vp.jpg",
    "media_type": "movie",
    "year": "2012",
    "animetv_url": "https://animetv.ge/169-talga-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_168",
    "tmdb_id": null,
    "name": "სააბაზანოს სული ჰანაკო (saabazanos suli hanako)",
    "original_name": "saabazanos suli hanako",
    "poster_path": "https://animetv.ge/uploads/posts/2026-05/1640201122_1623674311_1623674323.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/168-saabazanos-suli-hanako-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_167",
    "tmdb_id": null,
    "name": "სტრაიდის პრინცი (strideis princi)",
    "original_name": "strideis princi",
    "poster_path": "https://animetv.ge/uploads/posts/2026-05/1656670135_.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/167-strideis-princi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_166",
    "tmdb_id": null,
    "name": "დიდგვაროვანი (didgvarovani)",
    "original_name": "didgvarovani",
    "poster_path": "https://animetv.ge/uploads/posts/2026-05/1602265421_890.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/166-didgvarovani-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_165",
    "tmdb_id": 61421,
    "name": "ტერორის ექო (terror in resonance)",
    "original_name": "terror in resonance",
    "poster_path": "https://image.tmdb.org/t/p/w342/qa4an6FYwTXAeiOk5zHyZsJ4CNx.jpg",
    "media_type": "tv",
    "year": "2014",
    "animetv_url": "https://animetv.ge/165-terror-in-resonance-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_164",
    "tmdb_id": null,
    "name": "სუზუმე კარის საკეტი (suzume no tojimari suzume karis saketi)",
    "original_name": "suzume no tojimari suzume karis saketi",
    "poster_path": "https://animetv.ge/uploads/posts/2026-05/1685788715_1685788814.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/164-suzume-no-tojimari-suzume-karis-saketi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_141",
    "tmdb_id": 65930,
    "name": "ჩემი საგმირო აკადემია სეზონი 8 (my hero academia)",
    "original_name": "my hero academia",
    "poster_path": "https://image.tmdb.org/t/p/w342/phuYuzqWW9ru8EA3HVjE9W2Rr3M.jpg",
    "media_type": "tv",
    "year": "2016",
    "animetv_url": "https://animetv.ge/141-my-hero-academia-season-8-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_163",
    "tmdb_id": null,
    "name": "დრაკონის მისია: დაის თავგადასავალი (dragon quest the adventure of dai drakonis misia dais tavgadasavali)",
    "original_name": "dragon quest the adventure of dai drakonis misia dais tavgadasavali",
    "poster_path": "https://animetv.ge/uploads/posts/2026-04/1776532511.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/163-dragon-quest-the-adventure-of-dai-drakonis-misia-dais-tavgadasavali-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_162",
    "tmdb_id": 301022,
    "name": "მეგალო ბოქსი სეზონი 2 (megalo box)",
    "original_name": "megalo box",
    "poster_path": "https://animetv.ge/uploads/posts/2026-04/megalobox-s2-ii.webp",
    "media_type": "tv",
    "year": "2018",
    "animetv_url": "https://animetv.ge/162-megalo-box-season-2-nomad-megalo-boqsi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_161",
    "tmdb_id": 301022,
    "name": "მეგალო ბოქსი სეზონი 1 (megalo box)",
    "original_name": "megalo box",
    "poster_path": "https://animetv.ge/uploads/posts/2026-04/megalobox-s1.webp",
    "media_type": "tv",
    "year": "2018",
    "animetv_url": "https://animetv.ge/161-megalo-box-season-1-megalo-boqsi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_160",
    "tmdb_id": null,
    "name": "ოცნების გუნდი (ahiru no sora ocnebis gundi)",
    "original_name": "ahiru no sora ocnebis gundi",
    "poster_path": "https://animetv.ge/uploads/posts/2026-04/ocnebis-gundi.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/160-ahiru-no-sora-ocnebis-gundi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_159",
    "tmdb_id": null,
    "name": "შეიგრძენი ქარი (run with the wind sheigrdzeni qari)",
    "original_name": "run with the wind sheigrdzeni qari",
    "poster_path": "https://animetv.ge/uploads/posts/2026-04/wind-ragaca.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/159-run-with-the-wind-sheigrdzeni-qari-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_148",
    "tmdb_id": null,
    "name": "ყოვლისშემძლე არაოსტატი რომელიც მარტო მოქმედებს სეზონი 1 (jack of all trades s1)",
    "original_name": "jack of all trades s1",
    "poster_path": "https://animetv.ge/uploads/posts/2026-01/image.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/148-jack-of-all-trades-s1.html",
    "is_custom": true
  },
  {
    "id": "custom_158",
    "tmdb_id": 274671,
    "name": "დასაწყისი დასასრულის შემდეგ სეზონი 2 (the beginning after the end)",
    "original_name": "the beginning after the end",
    "poster_path": "https://image.tmdb.org/t/p/w342/u0QWnKUhxcxecQSclMBNnO5MXh.jpg",
    "media_type": "tv",
    "year": "2025",
    "animetv_url": "https://animetv.ge/158-the-beginning-after-the-end-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_156",
    "tmdb_id": 97617,
    "name": "აკადემიისთვის შეუფერებელი დემონთა ხელმწიფე: სეზონი 2 (misfit of demon king academy)",
    "original_name": "misfit of demon king academy",
    "poster_path": "https://image.tmdb.org/t/p/w342/xBNR7V4s5b0qQfRCiyEvIC5PS6v.jpg",
    "media_type": "tv",
    "year": "2020",
    "animetv_url": "https://animetv.ge/156-misfit-of-demon-king-academy-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_149",
    "tmdb_id": 95479,
    "name": "ჯუჯუცუ კაისენი: სეზონი 3 (jujutsu kaisen)",
    "original_name": "jujutsu kaisen",
    "poster_path": "https://image.tmdb.org/t/p/w342/fHpKWq9ayzSk8nSwqRuaAUemRKh.jpg",
    "media_type": "tv",
    "year": "2020",
    "animetv_url": "https://animetv.ge/149-jujutsu-kaisen-season-3-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_155",
    "tmdb_id": 1218925,
    "name": "მხერხავი: რეზეს არკა (chainsaw man reze arc)",
    "original_name": "chainsaw man reze arc",
    "poster_path": "https://image.tmdb.org/t/p/w342/xdzLBZjCVSEsic7m7nJc4jNJZVW.jpg",
    "media_type": "movie",
    "year": "2025",
    "animetv_url": "https://animetv.ge/155-chainsaw-man-reze-arc.html",
    "is_custom": true
  },
  {
    "id": "custom_154",
    "tmdb_id": 117465,
    "name": "ჯოჯოხეთის სამოთხე: სეზონი 2 (hells paradise)",
    "original_name": "hells paradise",
    "poster_path": "https://image.tmdb.org/t/p/w342/1V9I7SvZbYoMbSvdtnlkkq9SB1k.jpg",
    "media_type": "tv",
    "year": "2023",
    "animetv_url": "https://animetv.ge/154-hells-paradise-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_152",
    "tmdb_id": 88803,
    "name": "საგა ვინლანდიაზე სეზონი 2 (vinland saga)",
    "original_name": "vinland saga",
    "poster_path": "https://image.tmdb.org/t/p/w342/vUHlpA5c1NXkds59reY3HMb4Abs.jpg",
    "media_type": "tv",
    "year": "2019",
    "animetv_url": "https://animetv.ge/152-vinland-saga-season-2-saga-vinlandiaze-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_151",
    "tmdb_id": 88803,
    "name": "საგა ვინლანდიაზე სეზონი 1 (vinland saga)",
    "original_name": "vinland saga",
    "poster_path": "https://image.tmdb.org/t/p/w342/vUHlpA5c1NXkds59reY3HMb4Abs.jpg",
    "media_type": "tv",
    "year": "2019",
    "animetv_url": "https://animetv.ge/151-vinland-saga-season-1-saga-vinlandiaze-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_146",
    "tmdb_id": null,
    "name": "ფათი და მათი (ფათი და მათი)",
    "original_name": "ფათი და მათი",
    "poster_path": "https://animetv.ge/uploads/posts/2025-12/pat-and-mat-poster.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/146-ფათი-და-მათი.html",
    "is_custom": true
  },
  {
    "id": "custom_147",
    "tmdb_id": 1429,
    "name": "ტიტანების შემოტევა: სეზონი 1 (attack on titan)",
    "original_name": "attack on titan",
    "poster_path": "https://image.tmdb.org/t/p/w342/7GNLOPb9I6MkSMGzdEjZJawzkfk.jpg",
    "media_type": "tv",
    "year": "2013",
    "animetv_url": "https://animetv.ge/147-attack-on-titan-season-1-titanebis-shemoteva-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_140",
    "tmdb_id": 215799,
    "name": "დამარცხებული რეინჯერი: სეზონი 1 (go go loser ranger)",
    "original_name": "go go loser ranger",
    "poster_path": "https://image.tmdb.org/t/p/w342/1xLqRhNM41Xv0UZRZsHBhsnB1lx.jpg",
    "media_type": "tv",
    "year": "2024",
    "animetv_url": "https://animetv.ge/140-go-go-loser-ranger-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_139",
    "tmdb_id": 97617,
    "name": "აკადემიისთვის შეუფერებელი დემონთა ხელმწიფე: სეზონი 1 (misfit of demon king academy)",
    "original_name": "misfit of demon king academy",
    "poster_path": "https://image.tmdb.org/t/p/w342/xBNR7V4s5b0qQfRCiyEvIC5PS6v.jpg",
    "media_type": "tv",
    "year": "2020",
    "animetv_url": "https://animetv.ge/139-misfit-of-demon-king-academy-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_145",
    "tmdb_id": null,
    "name": "Valorant Cinematics (valorant cinematic)",
    "original_name": "valorant cinematic",
    "poster_path": "https://animetv.ge/uploads/posts/2025-11/valorant.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/145-valorant-cinematic-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_144",
    "tmdb_id": 63926,
    "name": "One punch man სეზონი 3 (one punch man)",
    "original_name": "one punch man",
    "poster_path": "https://image.tmdb.org/t/p/w342/dT10AxJIXVvRwFAew4tt2RhzJrD.jpg",
    "media_type": "tv",
    "year": "2015",
    "animetv_url": "https://animetv.ge/144-one-punch-man-season-3-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_48",
    "tmdb_id": null,
    "name": "ნაგავი (gachiakuta nagavi)",
    "original_name": "gachiakuta nagavi",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/gachiakuta.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/48-gachiakuta-nagavi-season-1-gachiakuta-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_142",
    "tmdb_id": null,
    "name": "საოცრებათა სამყარო მოკვდავთათვის წითელი დანის მფლობელი (deadman wonderland red knife wielder)",
    "original_name": "deadman wonderland red knife wielder",
    "poster_path": "https://animetv.ge/uploads/posts/2025-10/deadman_wonderland_ova.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/142-deadman-wonderland-red-knife-wielder-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_85",
    "tmdb_id": 207332,
    "name": "საკამოტოს დღეები სეზონი 1: ნაწილი 2 (sakamoto days)",
    "original_name": "sakamoto days",
    "poster_path": "https://image.tmdb.org/t/p/w342/wRpCqsJFyKNuh5FMegNPrhzp2NF.jpg",
    "media_type": "tv",
    "year": "2025",
    "animetv_url": "https://animetv.ge/85-sakamoto-days-season-1-part-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_138",
    "tmdb_id": 107408,
    "name": "ათლეტი სამურაი (the gymnastics samurai)",
    "original_name": "the gymnastics samurai",
    "poster_path": "https://image.tmdb.org/t/p/w342/liHoITCCyZr9EB6KKl9VqKLOQ5H.jpg",
    "media_type": "tv",
    "year": "2020",
    "animetv_url": "https://animetv.ge/138-the-gymnastics-samurai-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_137",
    "tmdb_id": 66991,
    "name": "ზესტრიის ზღაპრები: სეზონი 2 (tales of zestiria the x)",
    "original_name": "tales of zestiria the x",
    "poster_path": "https://image.tmdb.org/t/p/w342/8cvnUjctdbExvnRyo8AVDvo2KaT.jpg",
    "media_type": "tv",
    "year": "2016",
    "animetv_url": "https://animetv.ge/137-tales-of-zestiria-the-x-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_136",
    "tmdb_id": 66991,
    "name": "ზესტრიის ზღაპრები: სეზონი 1 (tales of zestiria the x)",
    "original_name": "tales of zestiria the x",
    "poster_path": "https://image.tmdb.org/t/p/w342/8cvnUjctdbExvnRyo8AVDvo2KaT.jpg",
    "media_type": "tv",
    "year": "2016",
    "animetv_url": "https://animetv.ge/136-tales-of-zestiria-the-x-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_135",
    "tmdb_id": 74096,
    "name": "უბრალოდ იმიტომ (just because)",
    "original_name": "just because",
    "poster_path": "https://image.tmdb.org/t/p/w342/b4Ap7g0egqBt9JJA5qNfpxq4jN2.jpg",
    "media_type": "tv",
    "year": "2017",
    "animetv_url": "https://animetv.ge/135-just-because-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_134",
    "tmdb_id": 74089,
    "name": "გარო - გაქრობის ხაზი (garo vanishing line)",
    "original_name": "garo vanishing line",
    "poster_path": "https://image.tmdb.org/t/p/w342/qZ6QbEjU2J829zSFyDJlHZaFYVe.jpg",
    "media_type": "tv",
    "year": "2017",
    "animetv_url": "https://animetv.ge/134-garo-vanishing-line-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_132",
    "tmdb_id": 98123,
    "name": "უკვდავი მეფის ყოველდღიური ცხოვრება: სეზონი 2 (the daily life of the immortal king)",
    "original_name": "the daily life of the immortal king",
    "poster_path": "https://image.tmdb.org/t/p/w342/7By0jV3kf9MVvv3X3K8u4mhRUwp.jpg",
    "media_type": "tv",
    "year": "2020",
    "animetv_url": "https://animetv.ge/132-the-daily-life-of-the-immortal-king-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_131",
    "tmdb_id": 98123,
    "name": "უკვდავი მეფის ყოველდღიური ცხოვრება: სეზონი 1 (the daily life of the immortal king)",
    "original_name": "the daily life of the immortal king",
    "poster_path": "https://image.tmdb.org/t/p/w342/7By0jV3kf9MVvv3X3K8u4mhRUwp.jpg",
    "media_type": "tv",
    "year": "2020",
    "animetv_url": "https://animetv.ge/131-the-daily-life-of-the-immortal-king-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_130",
    "tmdb_id": 158373,
    "name": "ნიერ: ავტომატა ვერსია 1.1ა (nier automata ver 11a)",
    "original_name": "nier automata ver 11a",
    "poster_path": "https://image.tmdb.org/t/p/w342/qHSCYOXHV3EKXKkMxUvC9rGx4Av.jpg",
    "media_type": "tv",
    "year": "2023",
    "animetv_url": "https://animetv.ge/130-nier-automata-ver-11a-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_129",
    "tmdb_id": 117465,
    "name": "ჯოჯოხეთის სამოთხე: სეზონი 1 (hells paradise)",
    "original_name": "hells paradise",
    "poster_path": "https://image.tmdb.org/t/p/w342/1V9I7SvZbYoMbSvdtnlkkq9SB1k.jpg",
    "media_type": "tv",
    "year": "2023",
    "animetv_url": "https://animetv.ge/129-hells-paradise-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_128",
    "tmdb_id": null,
    "name": "პრეზიდენტი მოახლედ! (the presidents maid prezidenti moakhled)",
    "original_name": "the presidents maid prezidenti moakhled",
    "poster_path": "https://animetv.ge/uploads/posts/2025-09/1586942925_.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/128-the-presidents-maid-prezidenti-moakhled-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_126",
    "tmdb_id": 82739,
    "name": "არამზადა, რომელსაც ბაჭია გოგონა არც კი დასიზმრებია (bunny girl senpai)",
    "original_name": "bunny girl senpai",
    "poster_path": "https://image.tmdb.org/t/p/w342/fbqDG7GjodvaNecgv1q8kfSNPl5.jpg",
    "media_type": "tv",
    "year": "2018",
    "animetv_url": "https://animetv.ge/126-bunny-girl-senpai-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_125",
    "tmdb_id": null,
    "name": "ანონიმური ხმა (anonimuri xma)",
    "original_name": "anonimuri xma",
    "poster_path": "https://animetv.ge/uploads/posts/2025-09/1627290486_2e5f4d0347dc5ee411a68c49b22a18d0-1.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/125-anonimuri-xma-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_124",
    "tmdb_id": null,
    "name": "მკვლელების კლასი სეზონი 2 (mkvlelebis klasi)",
    "original_name": "mkvlelebis klasi",
    "poster_path": "https://animetv.ge/uploads/posts/2025-09/mkvl-klasi-222.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/124-mkvlelebis-klasi-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_123",
    "tmdb_id": null,
    "name": "მკვლელების კლასი სეზონი 1 (mkvlelebis klasi)",
    "original_name": "mkvlelebis klasi",
    "poster_path": "https://animetv.ge/uploads/posts/2025-09/mkvl-klasi-1.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/123-mkvlelebis-klasi-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_122",
    "tmdb_id": null,
    "name": "ნარუტო ჯუჯუცუ კაისენი��� წინააღმდეგ (naruto vs jujutsu kaisen)",
    "original_name": "naruto vs jujutsu kaisen",
    "poster_path": "https://animetv.ge/uploads/posts/2025-09/nat-jjk.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/122-naruto-vs-jujutsu-kaisen-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_121",
    "tmdb_id": 61663,
    "name": "შენი აპრილის ტყუილი (your lie in april)",
    "original_name": "your lie in april",
    "poster_path": "https://image.tmdb.org/t/p/w342/92P9cD5uOzLVgx0QDTnwkXffjEG.jpg",
    "media_type": "tv",
    "year": "2014",
    "animetv_url": "https://animetv.ge/121-your-lie-in-april-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_120",
    "tmdb_id": 63926,
    "name": "One punch man სეზონი 2 (one punch man)",
    "original_name": "one punch man",
    "poster_path": "https://image.tmdb.org/t/p/w342/dT10AxJIXVvRwFAew4tt2RhzJrD.jpg",
    "media_type": "tv",
    "year": "2015",
    "animetv_url": "https://animetv.ge/120-one-punch-man-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_119",
    "tmdb_id": 63926,
    "name": "One Punch Man სეზონი 1 (one punch man)",
    "original_name": "one punch man",
    "poster_path": "https://image.tmdb.org/t/p/w342/dT10AxJIXVvRwFAew4tt2RhzJrD.jpg",
    "media_type": "tv",
    "year": "2015",
    "animetv_url": "https://animetv.ge/119-one-punch-man-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_118",
    "tmdb_id": 110070,
    "name": "ჰორიმია სეზონი 1 (horimiya)",
    "original_name": "horimiya",
    "poster_path": "https://image.tmdb.org/t/p/w342/iSOKGl5KIeOCAtigUDCfFZe2cOi.jpg",
    "media_type": "tv",
    "year": "2021",
    "animetv_url": "https://animetv.ge/118-horimiya-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_117",
    "tmdb_id": null,
    "name": "სხვა (another skhva)",
    "original_name": "another skhva",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1656847060_.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/117-another-skhva-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_116",
    "tmdb_id": null,
    "name": "ღამის გამოძახილი: სეზონი 1 (call of the night ghamis gamodakhili)",
    "original_name": "call of the night ghamis gamodakhili",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1669382918_.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/116-call-of-the-night-ghamis-gamodakhili-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_115",
    "tmdb_id": 45997,
    "name": "ბნელეთის ბატონი სამუშაოზე: სეზონი 2 (the devil is a part timer)",
    "original_name": "the devil is a part timer",
    "poster_path": "https://image.tmdb.org/t/p/w342/55jYHFT8iJuASF8Mzg0V8Dh3N3M.jpg",
    "media_type": "tv",
    "year": "2013",
    "animetv_url": "https://animetv.ge/115-the-devil-is-a-part-timer-season-2-bneltis-batoni-samushaoze-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_114",
    "tmdb_id": null,
    "name": "ბნელეთის ბატონი სამუშაოზე (the devil is a part timer bneltis batoni samushaoze)",
    "original_name": "the devil is a part timer bneltis batoni samushaoze",
    "poster_path": "https://animetv.ge/uploads/posts/2025-09/_png.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/114-the-devil-is-a-part-timer-bneltis-batoni-samushaoze-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_113",
    "tmdb_id": 67075,
    "name": "მობ ფსიქო 100: სეზონი 3 (mob psycho 100)",
    "original_name": "mob psycho 100",
    "poster_path": "https://image.tmdb.org/t/p/w342/vR7hwaGQ0ySRoq1WobiNRaPs4WO.jpg",
    "media_type": "tv",
    "year": "2016",
    "animetv_url": "https://animetv.ge/113-mob-psycho-100-season-3-mob-psiqo-100-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_112",
    "tmdb_id": 67075,
    "name": "მობ ფსიქო 100: სეზონი 2 (mob psycho 100)",
    "original_name": "mob psycho 100",
    "poster_path": "https://image.tmdb.org/t/p/w342/vR7hwaGQ0ySRoq1WobiNRaPs4WO.jpg",
    "media_type": "tv",
    "year": "2016",
    "animetv_url": "https://animetv.ge/112-mob-psycho-100-season-2-mob-psiqo-100-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_111",
    "tmdb_id": null,
    "name": "მობ ფსიქო 100: სეზო���ი 1 (mob psycho 100 mob psiqo 100)",
    "original_name": "mob psycho 100 mob psiqo 100",
    "poster_path": "https://animetv.ge/uploads/posts/2025-09/mob-fsiqooo.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/111-mob-psycho-100-mob-psiqo-100-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_110",
    "tmdb_id": null,
    "name": "სკოლა მურიმ (moorim school skola murim)",
    "original_name": "moorim school skola murim",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1547145470_59.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/110-moorim-school-skola-murim-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_108",
    "tmdb_id": 69237,
    "name": "ჯაჭვის ქრონიკა: სიკვდილის შუქი (chain chronicle the light of haecceitas jawvis qronika sikvdilis shuqi)",
    "original_name": "chain chronicle the light of haecceitas jawvis qronika sikvdilis shuqi",
    "poster_path": "https://image.tmdb.org/t/p/w342/9wBEr3ZSPukbb2rS6lRauyeDv19.jpg",
    "media_type": "tv",
    "year": "2017",
    "animetv_url": "https://animetv.ge/108-chain-chronicle-the-light-of-haecceitas-jawvis-qronika-sikvdilis-shuqi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_106",
    "tmdb_id": null,
    "name": "ჯუჯუცუ კაისენი 0 (jujutsu kaisen 0 filmi)",
    "original_name": "jujutsu kaisen 0 filmi",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1756450719.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/106-jujutsu-kaisen-0-filmi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_105",
    "tmdb_id": 95479,
    "name": "ჯუჯუცუ კაისენი სეზონი 2 (jujutsu kaisen)",
    "original_name": "jujutsu kaisen",
    "poster_path": "https://image.tmdb.org/t/p/w342/fHpKWq9ayzSk8nSwqRuaAUemRKh.jpg",
    "media_type": "tv",
    "year": "2020",
    "animetv_url": "https://animetv.ge/105-jujutsu-kaisen-season-2-jujutsu-kaisen-jujucu-kaiseni-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_104",
    "tmdb_id": 95479,
    "name": "ჯუჯუცუ კაისენი სეზონი 1 (jujutsu kaisen)",
    "original_name": "jujutsu kaisen",
    "poster_path": "https://image.tmdb.org/t/p/w342/fHpKWq9ayzSk8nSwqRuaAUemRKh.jpg",
    "media_type": "tv",
    "year": "2020",
    "animetv_url": "https://animetv.ge/104-jujutsu-kaisen-season-1-jujutsu-kaisen-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_103",
    "tmdb_id": null,
    "name": "ინიციალი დი: მეოთხე საფეხური (initial d meotxe safexuri)",
    "original_name": "initial d meotxe safexuri",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/4st.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/103-initial-d-meotxe-safexuri-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_102",
    "tmdb_id": null,
    "name": "ინიციალი დი: მესამე საფეხური (initial d mesame safexuri)",
    "original_name": "initial d mesame safexuri",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/3st.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/102-initial-d-mesame-safexuri-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_101",
    "tmdb_id": null,
    "name": "ინიციალი დი: მეორე საფეხური (initial d meore safexuri)",
    "original_name": "initial d meore safexuri",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/2st.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/101-initial-d-meore-safexuri-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_100",
    "tmdb_id": null,
    "name": "ინიციალი დი: პირველი საფეხური (initial d pirveli safexuri)",
    "original_name": "initial d pirveli safexuri",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1st.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/100-initial-d-pirveli-safexuri-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_99",
    "tmdb_id": 83097,
    "name": "დაპირებული არარსებული ქვეყანა სეზონი 2 (the promised neverland)",
    "original_name": "the promised neverland",
    "poster_path": "https://image.tmdb.org/t/p/w342/oBgRCpAbtMpk1v8wfdsIph7lPQE.jpg",
    "media_type": "tv",
    "year": "2019",
    "animetv_url": "https://animetv.ge/99-the-promised-neverland-season-2-dapirebuli-ararsebuli-qveyana-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_98",
    "tmdb_id": 83097,
    "name": "დაპირებული არარსებული ქვეყანა სეზონი 1 (the promised neverland)",
    "original_name": "the promised neverland",
    "poster_path": "https://image.tmdb.org/t/p/w342/oBgRCpAbtMpk1v8wfdsIph7lPQE.jpg",
    "media_type": "tv",
    "year": "2019",
    "animetv_url": "https://animetv.ge/98-the-promised-neverland-season-1-dapirebuli-ararsebuli-qveyana-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_97",
    "tmdb_id": 83100,
    "name": "დორორო (dororo)",
    "original_name": "dororo",
    "poster_path": "https://image.tmdb.org/t/p/w342/mLSJO9lj2RMHdzHJMNMoksmwlbv.jpg",
    "media_type": "tv",
    "year": "2019",
    "animetv_url": "https://animetv.ge/97-dororo-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_95",
    "tmdb_id": null,
    "name": "შამანთა მეფე (shaman king shamanta mefe)",
    "original_name": "shaman king shamanta mefe",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1664526478_-1.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/95-shaman-king-shamanta-mefe-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_94",
    "tmdb_id": 761898,
    "name": "ფარიკაობის ხელოვნება: პროგრესული - მოწმენდილი ღამის არია (sword art online progressive aria of a starless night farikaobis xelovneba progresuli mocmendili ghamis aria)",
    "original_name": "sword art online progressive aria of a starless night farikaobis xelovneba progresuli mocmendili ghamis aria",
    "poster_path": "https://image.tmdb.org/t/p/w342/yD9RhgIVydQNBK7OLEbCWYcWMUd.jpg",
    "media_type": "movie",
    "year": "2021",
    "animetv_url": "https://animetv.ge/94-sword-art-online-progressive-aria-of-a-starless-night-farikaobis-xelovneba-progresuli-mocmendili-ghamis-aria-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_93",
    "tmdb_id": 115911,
    "name": "ორიენტი სეზონი 2 (orient)",
    "original_name": "orient",
    "poster_path": "https://image.tmdb.org/t/p/w342/jE5cgpooUbp8XJK7tPlJxjz5kp5.jpg",
    "media_type": "tv",
    "year": "2022",
    "animetv_url": "https://animetv.ge/93-orient-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_92",
    "tmdb_id": 115911,
    "name": "ორიენტი სეზონი 1 (orient)",
    "original_name": "orient",
    "poster_path": "https://image.tmdb.org/t/p/w342/jE5cgpooUbp8XJK7tPlJxjz5kp5.jpg",
    "media_type": "tv",
    "year": "2022",
    "animetv_url": "https://animetv.ge/92-orient-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_91",
    "tmdb_id": null,
    "name": "შავი ლაგუნა სეზონი 1 (black lagoon shavi laguna season1)",
    "original_name": "black lagoon shavi laguna season1",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1644679232_1642335056_.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/91-black-lagoon-shavi-laguna-season1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_90",
    "tmdb_id": 1104844,
    "name": "ლურჯი საკეტი ეპიზოდი ნაგი (blue lock episode nagi)",
    "original_name": "blue lock episode nagi",
    "poster_path": "https://image.tmdb.org/t/p/w342/yZYZqT1f6rddhiSdjl8NVVCoZKE.jpg",
    "media_type": "movie",
    "year": "2024",
    "animetv_url": "https://animetv.ge/90-blue-lock-episode-nagi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_89",
    "tmdb_id": 131041,
    "name": "ლურჯი საკეტი ოცწლამდე იაპონიის წინააღმდეგ (blue lock)",
    "original_name": "blue lock",
    "poster_path": "https://image.tmdb.org/t/p/w342/fcKH1NQzoTXiYO1OrhaFFwTKhBp.jpg",
    "media_type": "tv",
    "year": "2022",
    "animetv_url": "https://animetv.ge/89-blue-lock-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_88",
    "tmdb_id": 131041,
    "name": "ლურჯი საკეტი (blue lock)",
    "original_name": "blue lock",
    "poster_path": "https://image.tmdb.org/t/p/w342/fcKH1NQzoTXiYO1OrhaFFwTKhBp.jpg",
    "media_type": "tv",
    "year": "2022",
    "animetv_url": "https://animetv.ge/88-blue-lock-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_87",
    "tmdb_id": 202284,
    "name": "ნინძა კამუი სეზონი 1 (ninja kamui)",
    "original_name": "ninja kamui",
    "poster_path": "https://image.tmdb.org/t/p/w342/A7mYSloFonDcQtHTqyLqEg9rIkh.jpg",
    "media_type": "tv",
    "year": "2024",
    "animetv_url": "https://animetv.ge/87-ninja-kamui-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_86",
    "tmdb_id": 42503,
    "name": "საოცრებათა სამყარო მოკვდავთათვის (deadman wonderland)",
    "original_name": "deadman wonderland",
    "poster_path": "https://image.tmdb.org/t/p/w342/wDwkvuslBsLZbZdiliU41w4DUdt.jpg",
    "media_type": "tv",
    "year": "2011",
    "animetv_url": "https://animetv.ge/86-deadman-wonderland-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_84",
    "tmdb_id": 207332,
    "name": "საკამოტოს დღეები სეზონი 1 (sakamoto days)",
    "original_name": "sakamoto days",
    "poster_path": "https://image.tmdb.org/t/p/w342/wRpCqsJFyKNuh5FMegNPrhzp2NF.jpg",
    "media_type": "tv",
    "year": "2025",
    "animetv_url": "https://animetv.ge/84-sakamoto-days-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_82",
    "tmdb_id": 82180,
    "name": "ძაღლები: ტყვიები და ხოცვა-ჟლეტა (dogs stray dogs howling in the dark)",
    "original_name": "dogs stray dogs howling in the dark",
    "poster_path": "https://image.tmdb.org/t/p/w342/iyC6Yhzw6hQ2lV6J7kUgTi4faBh.jpg",
    "media_type": "tv",
    "year": "2009",
    "animetv_url": "https://animetv.ge/82-dogs-stray-dogs-howling-in-the-dark-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_81",
    "tmdb_id": 274671,
    "name": "დასაწყისი დასასრულის შემდეგ სეზონი 1 (the beginning after the end)",
    "original_name": "the beginning after the end",
    "poster_path": "https://image.tmdb.org/t/p/w342/u0QWnKUhxcxecQSclMBNnO5MXh.jpg",
    "media_type": "tv",
    "year": "2025",
    "animetv_url": "https://animetv.ge/81-the-beginning-after-the-end-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_80",
    "tmdb_id": 280110,
    "name": "ჩემი საგმირო აკადემია არალეგალური მართლმსაჯულები სეზონი 1 (my hero academia vigilantes)",
    "original_name": "my hero academia vigilantes",
    "poster_path": "https://image.tmdb.org/t/p/w342/iv0cXt6uJGlTryWZNQMGyum4Pme.jpg",
    "media_type": "tv",
    "year": "2025",
    "animetv_url": "https://animetv.ge/80-my-hero-academia-vigilantes-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_79",
    "tmdb_id": 218843,
    "name": "შვიდი მომაკვდინებელი ცოდვა აპოკალიფსის 4 მხედარი: სეზონი 2 (seven deadly sins four knights of apocalypse)",
    "original_name": "seven deadly sins four knights of apocalypse",
    "poster_path": "https://image.tmdb.org/t/p/w342/6SWVJvCIC9B16u6wASZ8FEaNssz.jpg",
    "media_type": "tv",
    "year": "2023",
    "animetv_url": "https://animetv.ge/79-seven-deadly-sins-four-knights-of-apocalypse-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_78",
    "tmdb_id": 218843,
    "name": "შვიდი მომაკვდინებელი ცოდვა აპოკალიფსის 4 მხედარი: სეზონი 1 (seven deadly sins four knights of apocalypse)",
    "original_name": "seven deadly sins four knights of apocalypse",
    "poster_path": "https://image.tmdb.org/t/p/w342/6SWVJvCIC9B16u6wASZ8FEaNssz.jpg",
    "media_type": "tv",
    "year": "2023",
    "animetv_url": "https://animetv.ge/78-seven-deadly-sins-four-knights-of-apocalypse-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_77",
    "tmdb_id": 127532,
    "name": "სოლო ლეველინგი: სეზონი 2 (solo leveling)",
    "original_name": "solo leveling",
    "poster_path": "https://image.tmdb.org/t/p/w342/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg",
    "media_type": "tv",
    "year": "2024",
    "animetv_url": "https://animetv.ge/77-solo-leveling-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_76",
    "tmdb_id": 127532,
    "name": "სოლო ლეველინგი: სეზონი 1 (solo leveling)",
    "original_name": "solo leveling",
    "poster_path": "https://image.tmdb.org/t/p/w342/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg",
    "media_type": "tv",
    "year": "2024",
    "animetv_url": "https://animetv.ge/76-solo-leveling-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_75",
    "tmdb_id": null,
    "name": "სკოლის ძიძები (school babysitters skolis dzidzebi)",
    "original_name": "school babysitters skolis dzidzebi",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1692816013_.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/75-school-babysitters-skolis-dzidzebi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_74",
    "tmdb_id": null,
    "name": "უმაღლესი სკოლის ღმერთი (the god of high school umaglesi skolis gmerti)",
    "original_name": "the god of high school umaglesi skolis gmerti",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1593596429_d6d6c1123807a789458700f470be0062-1.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/74-the-god-of-high-school-umaglesi-skolis-gmerti-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_73",
    "tmdb_id": 67043,
    "name": "91 დღე (91 days)",
    "original_name": "91 days",
    "poster_path": "https://image.tmdb.org/t/p/w342/zrSxmvaHLvr6nqUOQ3R0uPl12v4.jpg",
    "media_type": "tv",
    "year": "2016",
    "animetv_url": "https://animetv.ge/73-91-days-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_72",
    "tmdb_id": null,
    "name": "ზომ 100: სიკვდილამდე შესასრულებელი სია (zom 100 sikvdilamde shesrulebadi sia)",
    "original_name": "zom 100 sikvdilamde shesrulebadi sia",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1689023780_100.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/72-zom-100-sikvdilamde-shesrulebadi-sia-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_71",
    "tmdb_id": null,
    "name": "მკვლელობის სიყვარული (koroshi ai mkvlelobis siyvaruli)",
    "original_name": "koroshi ai mkvlelobis siyvaruli",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/c2043566425ea81b.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/71-koroshi-ai-mkvlelobis-siyvaruli-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_70",
    "tmdb_id": null,
    "name": "ჟანგის მჭამელი ბისკო (rust eater bisco jangis mchameli bisko)",
    "original_name": "rust eater bisco jangis mchameli bisko",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1656670821_.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/70-rust-eater-bisco-jangis-mchameli-bisko-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_69",
    "tmdb_id": 61374,
    "name": "ტოკიო გოული: სეზონი 4 (tokyo ghoul)",
    "original_name": "tokyo ghoul",
    "poster_path": "https://image.tmdb.org/t/p/w342/1m4RlC9BTCbyY549TOdVQ5NRPcR.jpg",
    "media_type": "tv",
    "year": "2014",
    "animetv_url": "https://animetv.ge/69-tokyo-ghoul-season-4-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_68",
    "tmdb_id": 61374,
    "name": "ტოკიო გოული: სეზონი 3 (tokyo ghoul)",
    "original_name": "tokyo ghoul",
    "poster_path": "https://image.tmdb.org/t/p/w342/1m4RlC9BTCbyY549TOdVQ5NRPcR.jpg",
    "media_type": "tv",
    "year": "2014",
    "animetv_url": "https://animetv.ge/68-tokyo-ghoul-season-3-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_67",
    "tmdb_id": 61374,
    "name": "ტოკიო გოული: სეზონი 2 (tokyo ghoul)",
    "original_name": "tokyo ghoul",
    "poster_path": "https://image.tmdb.org/t/p/w342/1m4RlC9BTCbyY549TOdVQ5NRPcR.jpg",
    "media_type": "tv",
    "year": "2014",
    "animetv_url": "https://animetv.ge/67-tokyo-ghoul-season-2-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_66",
    "tmdb_id": 61374,
    "name": "ტოკიო გოული: სეზონი 1 (tokyo ghoul)",
    "original_name": "tokyo ghoul",
    "poster_path": "https://image.tmdb.org/t/p/w342/1m4RlC9BTCbyY549TOdVQ5NRPcR.jpg",
    "media_type": "tv",
    "year": "2014",
    "animetv_url": "https://animetv.ge/66-tokyo-ghoul-season-1-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_65",
    "tmdb_id": 66390,
    "name": "განგსტა (gangsta)",
    "original_name": "gangsta",
    "poster_path": "https://image.tmdb.org/t/p/w342/ly43ajQpjpYYnx3w5BgFtcflUTD.jpg",
    "media_type": "tv",
    "year": "2015",
    "animetv_url": "https://animetv.ge/65-gangsta-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_64",
    "tmdb_id": 1429,
    "name": "ტიტანების შემოტევა: სეზონი 4 (attack on titan)",
    "original_name": "attack on titan",
    "poster_path": "https://image.tmdb.org/t/p/w342/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
    "media_type": "tv",
    "year": "2013",
    "animetv_url": "https://animetv.ge/64-attack-on-titan-season-4-titanebis-shemoteva-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_63",
    "tmdb_id": 315288,
    "name": "მებრძოლი სული: სეზონი 2 (hajime no ippo)",
    "original_name": "hajime no ippo",
    "poster_path": "https://image.tmdb.org/t/p/w342/4aUO7AgGqh2KZcNBljr2cE0EVuC.jpg",
    "media_type": "tv",
    "year": "2013",
    "animetv_url": "https://animetv.ge/63-hajime-no-ippo-season-2-fighting-spirit-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_62",
    "tmdb_id": null,
    "name": "მებრძოლი სული: ჩემპიონის გზა (hajime no ippo movie)",
    "original_name": "hajime no ippo movie",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/ippo-champions-road.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/62-hajime-no-ippo-movie-qartulad-fighting-spirit.html",
    "is_custom": true
  },
  {
    "id": "custom_61",
    "tmdb_id": null,
    "name": "მებრძოლი სული: კიმურა მაშიბას წინააღმდეგ (hajime no ippo movie)",
    "original_name": "hajime no ippo movie",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/ippo-kimura-vs-mashiba.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/61-hajime-no-ippo-movie-qartulad-fighting-spirit.html",
    "is_custom": true
  },
  {
    "id": "custom_60",
    "tmdb_id": 315288,
    "name": "მებრძოლი სული სეზონი 1 (hajime no ippo)",
    "original_name": "hajime no ippo",
    "poster_path": "https://image.tmdb.org/t/p/w342/4aUO7AgGqh2KZcNBljr2cE0EVuC.jpg",
    "media_type": "tv",
    "year": "2013",
    "animetv_url": "https://animetv.ge/60-hajime-no-ippo-season-1-qartulad-fighting-spirit.html",
    "is_custom": true
  },
  {
    "id": "custom_58",
    "tmdb_id": null,
    "name": "შესრულებადი მისია (mission possible shesrulebadi misia)",
    "original_name": "mission possible shesrulebadi misia",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1659964174_.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/58-mission-possible-shesrulebadi-misia-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_57",
    "tmdb_id": 85937,
    "name": "დემონების მკვეთი ხმალი: სეზონი 4 (demon slayer kimetsu no yaiba)",
    "original_name": "demon slayer kimetsu no yaiba",
    "poster_path": "https://image.tmdb.org/t/p/w342/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
    "media_type": "tv",
    "year": "2019",
    "animetv_url": "https://animetv.ge/57-demon-slayer-kimetsu-no-yaiba-season-4-demonebis-mkveti-xmali-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_56",
    "tmdb_id": 85937,
    "name": "დემონების მკვეთი ხმალი: სეზონი 3 (demon slayer kimetsu no yaiba)",
    "original_name": "demon slayer kimetsu no yaiba",
    "poster_path": "https://image.tmdb.org/t/p/w342/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
    "media_type": "tv",
    "year": "2019",
    "animetv_url": "https://animetv.ge/56-demon-slayer-kimetsu-no-yaiba-season-3-demonebis-mkveti-xmali-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_55",
    "tmdb_id": 85937,
    "name": "დემონების მკვეთი ხმალი: სეზონი 2 (demon slayer kimetsu no yaiba)",
    "original_name": "demon slayer kimetsu no yaiba",
    "poster_path": "https://image.tmdb.org/t/p/w342/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
    "media_type": "tv",
    "year": "2019",
    "animetv_url": "https://animetv.ge/55-demon-slayer-kimetsu-no-yaiba-season-2-demonebis-mkveti-xmali-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_54",
    "tmdb_id": null,
    "name": "დემონების მკვეთი ხმალი: უსასრულო მატარებელი (demon slayer mugen train demonebis mkveti xmali usasrulo matarebeli)",
    "original_name": "demon slayer mugen train demonebis mkveti xmali usasrulo matarebeli",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/ds-movie.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/54-demon-slayer-mugen-train-demonebis-mkveti-xmali-usasrulo-matarebeli-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_53",
    "tmdb_id": 85937,
    "name": "დემონების მკვეთი ხმალი: სეზონი 1 (demon slayer kimetsu no yaiba)",
    "original_name": "demon slayer kimetsu no yaiba",
    "poster_path": "https://image.tmdb.org/t/p/w342/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
    "media_type": "tv",
    "year": "2019",
    "animetv_url": "https://animetv.ge/53-demon-slayer-kimetsu-no-yaiba-season-1-demonebis-mkveti-xmali-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_52",
    "tmdb_id": 105009,
    "name": "ტოკიოს შურისმაძიებლები: სეზონი 3 (tokyo revengers)",
    "original_name": "tokyo revengers",
    "poster_path": "https://image.tmdb.org/t/p/w342/arB3L9pZZBSzUPSC8BEv8c3X0bF.jpg",
    "media_type": "tv",
    "year": "2021",
    "animetv_url": "https://animetv.ge/52-tokyo-revengers-season-3-tokios-shurismadzieblebi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_51",
    "tmdb_id": 105009,
    "name": "ტოკიოს შურისმაძიებლები: სეზონი 2 (tokyo revengers)",
    "original_name": "tokyo revengers",
    "poster_path": "https://image.tmdb.org/t/p/w342/arB3L9pZZBSzUPSC8BEv8c3X0bF.jpg",
    "media_type": "tv",
    "year": "2021",
    "animetv_url": "https://animetv.ge/51-tokyo-revengers-season-2-tokios-shurismadzieblebi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_50",
    "tmdb_id": 105009,
    "name": "ტოკიოს შურისმაძიებლები: სეზონი 1 (tokyo revengers)",
    "original_name": "tokyo revengers",
    "poster_path": "https://image.tmdb.org/t/p/w342/arB3L9pZZBSzUPSC8BEv8c3X0bF.jpg",
    "media_type": "tv",
    "year": "2021",
    "animetv_url": "https://animetv.ge/50-tokyo-revengers-season-1-tokios-shurismadzieblebi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_35",
    "tmdb_id": null,
    "name": "ვან პისი (one piece van pisi)",
    "original_name": "one piece van pisi",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/s1-op.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/35-one-piece-van-pisi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_34",
    "tmdb_id": 428707,
    "name": "კუროკოს კალათბურთი: ფილმი - უკანასკნელი თამაში (kuroko no basuke the movie last game kurokos kalatburti filmi)",
    "original_name": "kuroko no basuke the movie last game kurokos kalatburti filmi",
    "poster_path": "https://image.tmdb.org/t/p/w342/mXJQbwxA0joNv9rGy25rFrm5N1r.jpg",
    "media_type": "movie",
    "year": "2017",
    "animetv_url": "https://animetv.ge/34-kuroko-no-basuke-the-movie-last-game-kurokos-kalatburti-filmi-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_33",
    "tmdb_id": 45783,
    "name": "კუროკოს კალათბურთი სეზონი 3 (kuroko no basuke)",
    "original_name": "kuroko no basuke",
    "poster_path": "https://image.tmdb.org/t/p/w342/qi8dlAgQEeahpEn1AOb5BJEOcVB.jpg",
    "media_type": "tv",
    "year": "2012",
    "animetv_url": "https://animetv.ge/33-kuroko-no-basuke-season-3-kurokos-kalatburti-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_32",
    "tmdb_id": 45783,
    "name": "კუროკოს კალათბურთი სეზონი 2 (kuroko no basuke)",
    "original_name": "kuroko no basuke",
    "poster_path": "https://image.tmdb.org/t/p/w342/qi8dlAgQEeahpEn1AOb5BJEOcVB.jpg",
    "media_type": "tv",
    "year": "2012",
    "animetv_url": "https://animetv.ge/32-kuroko-no-basuke-season-2-kurokos-kalatburti-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_31",
    "tmdb_id": 45783,
    "name": "კუროკოს კალათბურთი სეზონი 1 (kuroko no basuke)",
    "original_name": "kuroko no basuke",
    "poster_path": "https://image.tmdb.org/t/p/w342/qi8dlAgQEeahpEn1AOb5BJEOcVB.jpg",
    "media_type": "tv",
    "year": "2012",
    "animetv_url": "https://animetv.ge/31-kuroko-no-basuke-season-1-kurokos-kalatburti-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_30",
    "tmdb_id": 60863,
    "name": "ფრენბურთი!! მწვერვალისკენ სეზონი 4 (haikyuu)",
    "original_name": "haikyuu",
    "poster_path": "https://image.tmdb.org/t/p/w342/8WEr48swcqe89Zsy5sdrGCASlIg.jpg",
    "media_type": "tv",
    "year": "2014",
    "animetv_url": "https://animetv.ge/30-haikyuu-season-4-frrenburti-mtsvervalisken-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_29",
    "tmdb_id": 60863,
    "name": "ფრენბურთი!! მწვერვალისკენ სეზონი 3 (haikyuu)",
    "original_name": "haikyuu",
    "poster_path": "https://image.tmdb.org/t/p/w342/8WEr48swcqe89Zsy5sdrGCASlIg.jpg",
    "media_type": "tv",
    "year": "2014",
    "animetv_url": "https://animetv.ge/29-haikyuu-season-3-frrenburti-mtsvervalisken-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_28",
    "tmdb_id": 60863,
    "name": "ფრენბურთი!! მწვერვალისკენ სეზონი 2 (haikyuu)",
    "original_name": "haikyuu",
    "poster_path": "https://image.tmdb.org/t/p/w342/8WEr48swcqe89Zsy5sdrGCASlIg.jpg",
    "media_type": "tv",
    "year": "2014",
    "animetv_url": "https://animetv.ge/28-haikyuu-season-2-frrenburti-mtsvervalisken-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_27",
    "tmdb_id": 60863,
    "name": "ფრენბურთი!! მწვერვალისკენ სეზონი 1 (haikyuu)",
    "original_name": "haikyuu",
    "poster_path": "https://image.tmdb.org/t/p/w342/8WEr48swcqe89Zsy5sdrGCASlIg.jpg",
    "media_type": "tv",
    "year": "2014",
    "animetv_url": "https://animetv.ge/27-haikyuu-season-1-frrenburti-mtsvervalisken-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_26",
    "tmdb_id": 71018,
    "name": "შვიდი მომაკვდინებელი ცოდვა სეზონი 4 (nanatsu no taizai)",
    "original_name": "nanatsu no taizai",
    "poster_path": "https://image.tmdb.org/t/p/w342/tvJvByy99ul4hytAfNEboAFaFEY.jpg",
    "media_type": "tv",
    "year": "2017",
    "animetv_url": "https://animetv.ge/26-nanatsu-no-taizai-season-4-shvidi-momakvdinebeli-codva-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_25",
    "tmdb_id": 71018,
    "name": "შვიდი მომაკვდინებელი ცოდვა სეზონი 3 (nanatsu no taizai)",
    "original_name": "nanatsu no taizai",
    "poster_path": "https://image.tmdb.org/t/p/w342/tvJvByy99ul4hytAfNEboAFaFEY.jpg",
    "media_type": "tv",
    "year": "2017",
    "animetv_url": "https://animetv.ge/25-nanatsu-no-taizai-season-3-shvidi-momakvdinebeli-codva-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_24",
    "tmdb_id": 71018,
    "name": "შვიდი მომაკვდინებელი ცოდვა სეზონი 2 (nanatsu no taizai)",
    "original_name": "nanatsu no taizai",
    "poster_path": "https://image.tmdb.org/t/p/w342/tvJvByy99ul4hytAfNEboAFaFEY.jpg",
    "media_type": "tv",
    "year": "2017",
    "animetv_url": "https://animetv.ge/24-nanatsu-no-taizai-season-2-shvidi-momakvdinebeli-codva-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_23",
    "tmdb_id": 71018,
    "name": "შვიდი მომაკვდინებელი ცოდვა სეზონი 1 (nanatsu no taizai)",
    "original_name": "nanatsu no taizai",
    "poster_path": "https://image.tmdb.org/t/p/w342/tvJvByy99ul4hytAfNEboAFaFEY.jpg",
    "media_type": "tv",
    "year": "2017",
    "animetv_url": "https://animetv.ge/23-nanatsu-no-taizai-season-1-shvidi-momakvdinebeli-codva-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_22",
    "tmdb_id": null,
    "name": "ჩემი საგმირო აკადემია: შემდეგი შენ ხარ (my hero academia youre next chemi sagmiro akademia shemdengi shen xar)",
    "original_name": "my hero academia youre next chemi sagmiro akademia shemdengi shen xar",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/mha_youre_next_v2_my_version_desu.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/22-my-hero-academia-youre-next-chemi-sagmiro-akademia-shemdengi-shen-xar-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_21",
    "tmdb_id": null,
    "name": "ჩემი საგმირო აკადემია : მსოფლიო გმირების დავალება (my hero academia world heroes mission chemi sagmiro akademia msoflio gmirebis davaleba)",
    "original_name": "my hero academia world heroes mission chemi sagmiro akademia msoflio gmirebis davaleba",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1755131235.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/21-my-hero-academia-world-heroes-mission-chemi-sagmiro-akademia-msoflio-gmirebis-davaleba-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_20",
    "tmdb_id": null,
    "name": "ჩემი საგმირო აკადემია: გმირთა აღზევება (my hero academia heroes rising chemi sagmiro akademia gmirebta aghzeveba)",
    "original_name": "my hero academia heroes rising chemi sagmiro akademia gmirebta aghzeveba",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1755129913.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/20-my-hero-academia-heroes-rising-chemi-sagmiro-akademia-gmirebta-aghzeveba-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_19",
    "tmdb_id": null,
    "name": "ჩემი საგმირო აკადემია : ორი გმირი (my hero academia two heroes chemi sagmiro akademia ori gmiri)",
    "original_name": "my hero academia two heroes chemi sagmiro akademia ori gmiri",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/1755128154.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/19-my-hero-academia-two-heroes-chemi-sagmiro-akademia-ori-gmiri-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_18",
    "tmdb_id": null,
    "name": "ჩემი საგმირო აკადემია სეზონი 7 (my hero academia season7 chemi sagmiro akademia)",
    "original_name": "my hero academia season7 chemi sagmiro akademia",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/mha_s7.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/18-my-hero-academia-season7-chemi-sagmiro-akademia-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_17",
    "tmdb_id": null,
    "name": "ჩემი საგმირო აკადემია სეზონი 6 (my hero academia season6 chemi sagmiro akademia)",
    "original_name": "my hero academia season6 chemi sagmiro akademia",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/mha_s6.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/17-my-hero-academia-season6-chemi-sagmiro-akademia-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_16",
    "tmdb_id": null,
    "name": "ჩემი საგმირო აკადემია სეზონი 5 (my hero academia season5 chemi sagmiro akademia)",
    "original_name": "my hero academia season5 chemi sagmiro akademia",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/mha_s5.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/16-my-hero-academia-season5-chemi-sagmiro-akademia-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_15",
    "tmdb_id": null,
    "name": "ჩემი საგმირო აკადემია სეზონი 4 (my hero academia season4 chemi sagmiro akademia)",
    "original_name": "my hero academia season4 chemi sagmiro akademia",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/mha_s4.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/15-my-hero-academia-season4-chemi-sagmiro-akademia-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_14",
    "tmdb_id": null,
    "name": "ჩემი საგმირო აკადემია სეზონი 3 (my hero academia season3 chemi sagmiro akademia)",
    "original_name": "my hero academia season3 chemi sagmiro akademia",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/mha_s3.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/14-my-hero-academia-season3-chemi-sagmiro-akademia-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_13",
    "tmdb_id": null,
    "name": "ჩემი საგმირო აკადემია სეზონი 2 (my hero academia season2 chemi sagmiro akademia)",
    "original_name": "my hero academia season2 chemi sagmiro akademia",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/mha_s2.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/13-my-hero-academia-season2-chemi-sagmiro-akademia-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_12",
    "tmdb_id": null,
    "name": "შავი კლოვერი (black clover season1 shavi kloveri)",
    "original_name": "black clover season1 shavi kloveri",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/black-clover-old-poster-2.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/12-black-clover-season1-shavi-kloveri-qartulad.html",
    "is_custom": true
  },
  {
    "id": "custom_11",
    "tmdb_id": null,
    "name": "ჩემი საგმირო აკადემია სეზონი 1 (my hero academia season1 chemi sagmiro akademia)",
    "original_name": "my hero academia season1 chemi sagmiro akademia",
    "poster_path": "https://animetv.ge/uploads/posts/2025-08/mha_s1.webp",
    "media_type": "tv",
    "year": null,
    "animetv_url": "https://animetv.ge/11-my-hero-academia-season1-chemi-sagmiro-akademia-qartulad.html",
    "is_custom": true
  }
];